### ISSUE TITLE
Pinging @everyone?

### ISSUE THREAD

**Issue by WallyOxen** [jos-b/webhook-discord#17]
Hi, some of the ways I would like to integrate this are to have it ping everyone on certain messages. However it seems that even though I send a message with @everyone it shows up with the highlight around the word but doesn't actually ping users and the entire message doesn't turn orange as if someone sent it. 
Example: https://imgur.com/a/9NM2qzV

**Comment by jos-b** [comment]
This is a Discord limitation, mentions in embeds are not counted as pings. There are ways to make invisible-everyone pings in webhooks which I could look into for a future release, but for now, I'll be closing this as the question does not have an immediate fix.

**Comment by MrZillaGold** [comment]
@jos-b What do you think about the fix?
This function is really needed.

**Comment by jos-b** [comment]
@MrZillaGold Please read above. This is a discord limitation, not mine.

**Comment by jos-b** [comment]
If you set the text of the message to `[](@everyone)` then the webhook will invisibly ping everyone.
