### ISSUE TITLE
Problem when starting the program.

### ISSUE THREAD

**Issue by lucas-luchack** [jos-b/webhook-discord#30]
![image](https://user-images.githubusercontent.com/39491773/57412685-ceacd100-71f1-11e9-9b61-7ef2aec4fd3c.png)

**It works locally but not on the servers!**

**Comment by jos-b** [comment]
Interesting, are you using `"use strict";` anywhere? What Node version are you on?

**Comment by jos-b** [comment]
I'd be fine with adding a `"use strict";` to prevent this error but I'm interested as to the node version so I can test it.

**Comment by lucas-luchack** [comment]
Hello,
Node 4.8.2

**Comment by lucas-luchack** [comment]
Hello is not working on Node V5.12.0 and my version is Node V4.8.2

**Comment by lucas-luchack** [comment]
Hello,
I fixed the problem by installing a new version of NodeJS manually and **it works**!

*I still advise you to fix the problem so that it doesn't happen again!*

Sincerely!

**Comment by AthenasEngineering** [comment]
There's nothing really to fix.  The version you specified are no longer really supported by the foundation, and haven't been for quite a while.

**Comment by jos-b** [comment]
Yep, for the reason above I am closing this.
