### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by davkms** [jos-b/webhook-discord#31]
Is there not a way to add a avatar to the webhook? (without doing it manually)

**Comment by jos-b** [comment]
As of now no there is no support for that. Once I've finished exam season I can add this.

**Comment by jos-b** [comment]
Version 3.3.0 has been released to NPM including this change.

**Comment by davkms** [comment]
ayy, nice work

**Comment by Neguhs** [comment]
In order to apply avatar to webhooks is it msg.setAvatar() ?

**Comment by davkms** [comment]
i believe so

Den sön 8 sep. 2019 04:20Justin <notifications@github.com> skrev:

**Comment by Neguhs** [comment]
unfortunately .setAvatar() isn't a function
