### ISSUE TITLE
Footer Icon

### ISSUE THREAD

**Issue by siliconesi** [jos-b/webhook-discord#32]
Is there any way with the webhook builder to add a footer icon?

I do - 
.setFooter("TEXT", 'IMAGE URL HERE');

It won't provide me with an image on the message?

**Comment by jos-b** [comment]
Footer only accepts the text, there is no argument for image URL.

https://github.com/jos-b/webhook-discord/blob/f8aedfe83ff6700e39c94a04ab0ea2a02c754c00/lib/builder.js#L31-L39

I'll add footer images after exam season.

**Comment by jos-b** [comment]
Sorry, didn't mean to close this.

**Comment by siliconesi** [comment]
Would there be a possibility to allow images?

**Comment by siliconesi** [comment]
I think this would be a good addition

**Comment by jos-b** [comment]
Yes, I have just said I will add them after exam season, hence why the enhancement label as been added.

**Comment by siliconesi** [comment]
Perfect! Thanks for the quick update, keep revising!

**Comment by siliconesi** [comment]
Another addition - possibility to .seturl('URL HERE') for the Title!

**Comment by jos-b** [comment]
Version 3.3.0 has been released to NPM including this change.
