### ISSUE TITLE
Set Image

### ISSUE THREAD

**Issue by floodlock** [jos-b/webhook-discord#35]
when i'm trying to do
.setImage(guild.iconURL)
the webhook is being sent without an image any reason why? Im not getting any errors shown to me so i'm not sure if its something i done wrong

**Comment by jos-b** [comment]
Could you share some code, I'm pretty sure I tested this locally. What format is the icon URL? I'll look into it this weekend if you can get me some more info.

**Comment by floodlock** [comment]
okay turns out it wasn't an issue with the module, the issue was that the guild i was testing this on returned a null value for the url for some apparent reason. could you by any chance have an error pop out when theirs no url specified for .setImage( )
if you can't then that is fine and u can close this issue. sorry if i took up any important time

**Comment by jos-b** [comment]
No worries, a warning being emitted when fields are set to undefined sounds reasonable.

Once I'm finished with exams I'll add it :+1:

**Comment by jos-b** [comment]
Version 3.3.0 has been released to NPM including this change.
