### ISSUE TITLE
Attempting to use hyperlinks with addFields()

### ISSUE THREAD

**Issue by Neguhs** [jos-b/webhook-discord#36]
I've been trying to use hyperlinks but when the webhook is posted to my server it comes out as standard html

**Comment by jos-b** [comment]
Discord webhook hyperlinks do not use HTML, they use markdown syntax.

To add inline links [such as this](https://github.com/jos-b/webhook-discord/issues/36) you must use the following syntax:
```md
[link text](https://my.link/)
```

**Comment by Neguhs** [comment]
Thank you! I end up figuring out sooner! Thank you making this package it’s very useful
