### ISSUE TITLE
Missing Typings

### ISSUE THREAD

**Issue by Exitare** [jos-b/webhook-discord#37]
Hey, 
great module. It would be even better with typings. 
Do you see a chance to add those?

Best

**Comment by jos-b** [comment]
Hey there, I'm not primarily a JavaScript developer so I am clueless about typings, if you are willing to PR them to the repo it would be greatly appreciated.

**Comment by Exitare** [comment]
ok, i´ll get back here asap.

**Comment by jos-b** [comment]
Any updates on this?

**Comment by jos-b** [comment]
Would be nice to get this in before version 4.

**Comment by Exitare** [comment]
@jos-b  
it was weekend. Also I´m NA. 
Release date for v4? i am working on other projects aswell. but i´ll try to start today

**Comment by jos-b** [comment]
No rush, was just wondering for an ETA, I'm willing to hold off V4 for this.

**Comment by Exitare** [comment]
There are two ways to add typings. 
First is adding them directly to the repo, 2. adding them via pull request to this [repo](https://github.com/DefinitelyTyped/DefinitelyTyped) so types can be installed via @types/webhook-discord. 
What is you preferred apporach?
The second one would be not connected to your roadmap.

**Comment by jos-b** [comment]
What are the benefits of each? I'd rather do this repo.

**Comment by Exitare** [comment]
not everyone is using typescript, so for js devs types are useless.

**Comment by jos-b** [comment]
I plan to make breaking API changes pretty soon so I think it would be better to keep it here.

**Comment by Exitare** [comment]
is there another way to comunicate? i need to dig into your code and search and guess for the correct types. if i could talk to you directly it would be easier to generate them

**Comment by jos-b** [comment]
You can find me on Discord as `joseph#1337` or Twitter `@JosephTehDev`
