### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by jos-b** [jos-b/webhook-discord#38]
Should look into software for auto-generating documentation for the module.

**Comment by JoelDesante** [comment]
Yes, Please do this

**Comment by jos-b** [comment]
@JoelDesante Would you be interested in looking into this? I can look into some form of hosting on GitHub pages maybe but I'm not sure what technology people commonly use, would love to know what the community would like on this one.

**Comment by JoelDesante** [comment]
@jos-b 
After a quick google search I have found the following.

https://docsify.js.org/
or
https://www.gitbook.com/

Im sure these will be sufficient.

**Comment by jos-b** [comment]
Great news my friends!

https://jos-b.github.io/webhook-discord/

We have docs!
