### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by Maciek737** [jos-b/webhook-discord#52]
Hello just pointing out some missing features from the webhook api:

.setURL() - missing
.setDescription() - missing
.setAuthor() - missing

inline fields seem not to be working at the moment 

If these elements get fixed/added that would be fantastic! 

Thank you for your work :)

**Comment by Maciek737** [comment]
also .setTitle() is not listed but it works

**Comment by jos-b** [comment]
setDescription works already, setAuthor and setURL have been implemented in #54
